### ISSUE TITLE
Need UW NetIDs for Canvas and Course Email Lists

### ISSUE THREAD

**Issue by jayfo** [uwcse440/web-cse440-wi19#24]
- [x] Annie in Canvas
- [x] Manaswi in Canvas
- [x] Jeremy in Canvas
- [x] Mandy in Canvas

- [x] Annie in Course Mailing List
- [x] Manaswi in Course Mailing List
- [x] Jeremy in Course Mailing List
- [x] Mandy in Course Mailing List

**Comment by jayfo** [comment]
@uwcse440/autumn-2019-staff : need these from everybody

**Comment by aman100100** [comment]
My uw net ID is **manxu**

**Comment by manaswis** [comment]
my net ID is manaswi

**Comment by jayfo** [comment]
@Jerviny2 : Need a NetID to get you access for Canvas in the morning

**Comment by jayfo** [comment]
Manaswi says it's the same as your GitHub idea
