### ISSUE TITLE
Resolve Organization of Friday Brainstorm

### ISSUE THREAD

**Issue by jayfo** [uwcse440/web-cse440-wi19#26]
@manaswis : How did you run the 1st week brainstorm in Autumn?

I'd like to know this by Wednesday so we can confirm that same structure sounds good for this Friday.

**Comment by manaswis** [comment]
Here are the weekly slides for Friday sessions from last quarter: https://drive.google.com/drive/folders/175YH_5tW4-0kRyTYzMzRGTjg9wUqGWbQ?usp=sharing

And here is the link for week 1 on project brainstorming: https://docs.google.com/presentation/d/1zVo1nSADZuBVqIKB59jRyJZTJgc127naVcydX4sPQd0/edit?usp=sharing
