### ISSUE TITLE
Create, Links, and include Rubrics for Assignments in Canvas and Website

### ISSUE THREAD

**Issue by jayfo** [uwcse440/web-cse440-wi19#29]
- [x] Create Assignment 1 Submissions in Canvas
- [x] Create Assignment 2 Submissions in Canvas
- [x] Create Assignment 3 Submissions in Canvas
- [x] Create Assignment 4 Submissions in Canvas
- [x] Create Readings Submissions in Canvas

- [x] Embed Assignment 1 Due Dates and Links in Website
- [x] Embed Assignment 2 Due Dates and Links in Website
- [x] Embed Assignment 3 Due Dates and Links in Website
      https://github.com/uwcse440/web-cse440-wi19/blob/master/angular-workspace/src/app/assignments/assignment3/assignment3.component.pagedata.ts
- [x] Embed Assignment 4 Due Dates and Links in Website
      https://github.com/uwcse440/web-cse440-wi19/blob/master/angular-workspace/src/app/assignments/assignment4/assignment4.component.pagedata.ts
- [x] Embed Readings Due Dates and Links in Website
      https://github.com/uwcse440/web-cse440-wi19/blob/master/angular-workspace/src/app/assignments/readings/readings.component.pagedata.ts

- [x] Update Rubrics in Assignment 1 in Website
- [x] Update Rubrics in Assignment 2 in Website
- [x] Update Rubrics in Assignment 3 in Website
      https://github.com/uwcse440/web-cse440-wi19/blob/master/angular-workspace/src/app/assignments/assignment3/assignment3.component.content.md
- [x] Update Rubrics in Assignment 4 in Website
      https://github.com/uwcse440/web-cse440-wi19/blob/master/angular-workspace/src/app/assignments/assignment4/assignment4.component.content.md
- [x] Create Rubrics for Readings in Website
      https://github.com/uwcse440/web-cse440-wi19/blob/master/angular-workspace/src/app/assignments/readings/readings.component.content.md

- [x] Put Rubrics for Assignment 1 in Canvas
- [ ] Put Rubrics for Assignment 2 in Canvas
- [ ] Put Rubrics for Assignment 3 in Canvas
- [ ] Put Rubrics for Assignment 4 in Canvas
- [ ] Put Rubrics for Readings in Canvas

**Comment by annie-r** [comment]
@manaswis I'll do assignment 1 and 2, you do 3 and 4?

**Comment by annie-r** [comment]
for group assignments, are we grading each student independently?

**Comment by manaswis** [comment]
Groups are graded by group that we create on canvas. So all the students are assigned the same grade.

**Comment by jayfo** [comment]
Correct, we'll configure project groups in Canvas after we assign them.  Then you give the grade once, they all get the same grade.

**Comment by jayfo** [comment]
@annie-r and @manaswis , I've broken down what I think we still need here.

Now that all the readings are posted, I don't think I'm blocking on anything here. Can we get it resolved?

**Comment by manaswis** [comment]
To add: Update deadlines for assignment 3 and 4.

**Comment by manaswis** [comment]
Reading dates are now updated on Canvas.

**Comment by jayfo** [comment]
I changed the "Embed Links" tasks to "Embed Due Dates and Links".

**Comment by annie-r** [comment]
made pull request for adding Assignment 3 canvas links to website

**Comment by jayfo** [comment]
Split the rubrics out into other issues.

**Comment by manaswis** [comment]
Rubric for all assignments updated on canvas. The last points can be checked.
