### ISSUE TITLE
Try Again to Get Calendar Anchor Links Working

### ISSUE THREAD

**Issue by jayfo** [uwcse440/web-cse440-wi19#33]

**Comment by manaswis** [comment]
Assignment 3a (https://courses.cs.washington.edu/courses/cse440/19wi/assignments/assignment3#id-3a-paper_prototype), 3b (https://courses.cs.washington.edu/courses/cse440/19wi/assignments/assignment3#id-3b-heuristic-evaluation) and 3f (https://courses.cs.washington.edu/courses/cse440/19wi/assignments/assignment3#id-3f-final_report) are not working. However, 3c,3d, 3e, and 3g links work.

**Comment by jayfo** [comment]
This should be fixed in #47.
