### ISSUE TITLE
Get Github IDs and Add Staff to Repository

### ISSUE THREAD

**Issue by jayfo** [uwcse440/web-cse440-wi19#4]
- [x] Annie invited
- [x] Annie joined
- [x] Manaswi invited
- [x] Manaswi joined
- [x] Jeremy invited
- [x] Jeremy joined
- [x] Mandy invited
- [x] Mandy joined

**Comment by aman100100** [comment]
Hi, this is Mandy. My ID is aman100100 (manxu@uw.edu)
