### ISSUE TITLE
Assignments tab on the navbar links to Assignment 2

### ISSUE THREAD

**Issue by manaswis** [uwcse440/web-cse440-wi19#50]
Is this intentional OR does it automatically determine the current assignment and update the navbar accordingly?

![image](https://user-images.githubusercontent.com/2873216/51946188-aaad4880-23d5-11e9-9d1e-60f75ced3355.png)

**Comment by jayfo** [comment]
I've done that for now since it's the "primary" assignment.  Figured I was saving people a click?

**Comment by jayfo** [comment]
#wontfix
