### ISSUE TITLE
Add "Clarity and Presentation" Points to Rubrics in Assignment 3 and 4

### ISSUE THREAD

**Issue by jayfo** [uwcse440/web-cse440-wi19#64]
As we already did in Assignments 1 and 2, go through 3 and 4 to add:

`__Clarity and Presentation__: (2 points)`

everywhere that it's appropriate. Check the points to make sure these 2 are not overly weighted, increase the other points if necessary.

https://github.com/uwcse440/web-cse440-wi19/blob/master/angular-workspace/src/app/assignments/assignment3/assignment3.component.content.md

https://github.com/uwcse440/web-cse440-wi19/blob/master/angular-workspace/src/app/assignments/assignment4/assignment4.component.content.md

**Comment by jayfo** [comment]
@annie-r and @manaswis : Let's get this resolved today.

**Comment by manaswis** [comment]
Done - both website and canvas.
